### ISSUE TITLE
hi carlos this is my new ethereum wallet

### ISSUE THREAD

**Issue by rroopstr** [C4rlosM4tos/HOPE#3]
0x06467b517c49B82872db53BD2D9d0bB1c8D24B6f

**Comment by rroopstr** [comment]
carlos i think i made it hope is added to my brave browser 
0
HOPE

Enviar

Intercambiar
No tienes transacciones

**Comment by C4rlosM4tos** [comment]
change network to Fantom opera: 'brave: go to crypto wallets, top right corner select network, navigate to custom rpc, add the data provided by: https://docs.fantom.foundation/tutorials/set-up-metamask 

if you change the network to Fantom, and you add the token contract (hope on fantom) to assets then you should see 1 Hope, and i also send you 0.5 ftm for fees... ps: 1 gas is enough

**Comment by C4rlosM4tos** [comment]
total market cap shows 2, but there is only 1... i might mint more later, but i'm still making the font-end... i'm doing this all for free, so i'm not very motivated...  btw, everyone can mint hope, but it cost FTM to do so. the ftm is stored in the contract, if you want to sell hope, you can claim ftm back from the contract.... you will need to wait for my website, or you need to figure it out yourself how to

**Comment by C4rlosM4tos** [comment]
so its a bit confusing, but there is a hope coin backed by Eth running on the main chain of Eth, and listed on uniswap, that is not the coin i'm giving to you.... since fees on eth are so high, i decided to continue building on fantom

**Comment by C4rlosM4tos** [comment]
can you confirm you have hope?

**Comment by rroopstr** [comment]
let me check all you have responded

**Comment by rroopstr** [comment]
i succesfully created the fantom opera network on my wallet what is next

**Comment by rroopstr** [comment]
yes i have 0.5 FTM

**Comment by rroopstr** [comment]
why don't i have 1 i think we need to migrate all this discussion here and bitmex trollbox only for trading

**Comment by C4rlosM4tos** [comment]
but do you have 1 hope? see assets tap, if yhou don't see it, add the hope coin contract address, its on this github page at the bottom

**Comment by C4rlosM4tos** [comment]
*** CONTRACT RUNNING ON FANTOM CHAIN (live) ***
0x9f166e3d840FF8804AF9E867BA5Cfc1cd1cF2Ca1

**Comment by C4rlosM4tos** [comment]
don't forget to lower the gas when you use fantom,  the plugin might suggest main net fees, 1 wei is enough

**Comment by rroopstr** [comment]
my assets tab has exactly 0.5 hope

**Comment by rroopstr** [comment]
success Account 1 / HOPE


1
HOPE

Enviar

Intercambiar
No tienes transacciones

**Comment by C4rlosM4tos** [comment]
[
![image](https://user-images.githubusercontent.com/20709804/110256576-e134f480-7f99-11eb-9ac1-1872804fd7d7.png)
](url)

**Comment by C4rlosM4tos** [comment]
i have no styles or layout yet, just playing around and testing what is possible (for me)
you could help with art, colors, possible layouts... you now have the hope coin, but we still need to give it value...

**Comment by rroopstr** [comment]
ok what should i do now? keep it in the wallet i guess........

**Comment by C4rlosM4tos** [comment]
i might make some project page where you will be able to stake your hope coin, in reward you get the tokens from the project + your hope coin back (if you don't go through with funding, just staking it short time, but stuff for later)

**Comment by rroopstr** [comment]
i see what you mean..... i would need first to see who in my team is interested.... everyone is confused at me because they don't understand why i have a sudden emphasis in crypto, a lot of people just want to dismiss the subject.

**Comment by C4rlosM4tos** [comment]
i don't have a team... you would be the team ;)

**Comment by C4rlosM4tos** [comment]
there is a 2% difference between bid and ask price on the contract. that gap is added to the value of the coin, so hope should only go up, no matter if they buy or sell the coin... however, since its backed by ftm... if ftm goes to 0, so does hope. and the market cap of ftm is the virutal market cap of hope. (never going to happen ofc)

**Comment by C4rlosM4tos** [comment]
Venezuelans could make nft (erc721 cryptokitties art), and get paid in crypto when the item is sold. no need for borders or export... just to name any... i hope the people over there can see the value of blockchain and crypto. 

also, you should be able to send hope to the people you want...
hope has 18 decimals, so you can send 1*10**-18 hope if you want.
its not much worth in terms of money, but you can see it as sending REAL HOPE, like we burn candles for people if we hope things for them ;).
its also why i send you some FTM with it, otherwise you would need to buy ftm to move hope coins... just like  you need to buy eth to move some ERC20 poopcoin... i'm not the smartest guy, but if you want to know anything then just ask and i will see if i know it or not :)
